### ISSUE TITLE
Project 4

### ISSUE THREAD

**Issue by mariyawhitcomb** [ga-dc/wdi7-project4-gallery#41]
Link to repo:
Backend: https://github.com/mariyawhitcomb/gratitude-django
Frontend: https://github.com/mariyawhitcomb/gratitude_native
Link to deployed app:
I have not been able to deploy the app yet.

Things you'd like specific feedback on:

**Comment by ZakkMan** [comment]
@mariyawhitcomb have you deployed this yet?

**Comment by mariyawhitcomb** [comment]
Not yet..
